B.pyを作りました #1
kitakawaayano/gitremote2 pull request #6
Opened 2024-10-31 03:32 UTC by komakomahi

レビューお願いいたします。
close #1

2024-10-31 03:35 UTC, eisuke-nakanishi-4243121 commented on B.py
> +def hallo():
ハローの綴りが違います

2024-10-31 03:40 UTC, eisuke-nakanishi-4243121 requested changes

2024-10-31 03:40 UTC, eisuke-nakanishi-4243121 commented on B.py
> +def hallo():
```suggestion
def hello():
```
こんな感じでどうでしょう

2024-10-31 03:40 UTC, ja-kanno4A requested changes

2024-10-31 03:40 UTC, ja-kanno4A commented on B.py
> +def hallo():
```suggestion
def hello():
```

2024-10-31 03:42 UTC, ja-kanno4A commented on B.py
> +   print("こんにちは”)
```suggestion
   print("こんにちは")
```
” (全角)→ "(半角)

2024-11-01 02:24 UTC, eisuke-nakanishi-4243121 approved these changes
完璧でございます

2024-11-01 02:25 UTC, eisuke-nakanishi-4243121 approved these changes
おっけーです

2024-11-01 02:25 UTC, ja-kanno4A approved these changes
nice ;)

2024-11-01 02:26 UTC, merged